spring:
#  datasource:
#      username: root
#      password: "admin"
#      url: "jdbc:mysql://localhost:3306/mysql"
#      driverClassName: "com.mysql.cj.jdbc.Driver"

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.MySQL5Dialect    MYISAM


  redis:
    host: localhost
    port: 6379